mybatis:
   mapper-locations: classpath:/sqlmap/sqlmapper_*.xml
   type-aliases-package: com.data.batch.vo
   
spring :
   datasource :
      driver-class-name : com.mysql.cj.jdbc.Driver
      url : jdbc:mysql://sangwon-database.csnd3edwjp9u.ap-northeast-2.rds.amazonaws.com:3306/applyhome?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC 
      username : admin
      password : tkddnjs0823